### ISSUE TITLE
New release with `make install`

### ISSUE THREAD

**Issue by hwhelchel** [graphql/libgraphqlparser#18]
Hello! Thank you for your open source contribution. We're trying to package this up for easy install through Homebrew and are using the 0.1.0 release tag for the `tar.gz` packaging. However 0.1.0 doesn't have the `make install` task. Could you please create a new release with the `make install` task?

Thanks!

https://github.com/Homebrew/homebrew/pull/44389

**Comment by swolchok** [comment]
Here you go. Glad you want to put this in Homebrew, that's awesome! https://github.com/graphql/libgraphqlparser/releases/tag/v0.2.0
