### ISSUE TITLE
Out of source build not possible, CMakeLists assumes building from root

### ISSUE THREAD

**Issue by daniel-j-h** [graphql/libgraphqlparser#2]
The custom commands in the [CmakeLists](https://github.com/graphql/libgraphqlparser/blob/782e19b8ff891419bd3908d85cc6183f0e6d57e3/CMakeLists.txt#L43-L77) are hardcoded to expect building from the root directory.

Steps to reproduce:

    > mkdir build && cd build
    > cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build .

Filtered warnings:

> python: can't open file './ast/ast.py': [Errno 2] No such file or directory

It would be great to allow or even prefer out of source builds.

**Comment by swolchok** [comment]
Thanks for the bug report! When we do an out-of-source build, would you expect the generated source code files (both bison output like `parser.tab.cpp` and custom AST generation output like `Ast.h`) to go in the out-of-source build directory or still in the main source tree?

**Comment by daniel-j-h** [comment]
Good question. I would say build directory, since they are artefacts of the build system (and could _potentially_ change between builds, although they do not right now). And if I need them for interacting with the library, maybe the installation target could take care of placing them in the right location.

**Comment by swolchok** [comment]
Can you please check whether #4 makes things better for you?

**Comment by daniel-j-h** [comment]
Unfortunately, linking now fails:

https://gist.github.com/daniel-j-h/a2d3045b5eb7775e2779

**Comment by swolchok** [comment]
Thanks for checking! I fixed Travis CI for this repo and I think the latest version works. Will merge it soon.
