### ISSUE TITLE
Structure of installation, includes and usages

### ISSUE THREAD

**Issue by fxfactorial** [graphql/libgraphqlparser#26]
@swolchok Great work, reached out to you on twitter as well. 

I am doing OCaml bindings, https://github.com/fxfactorial/ocaml-graphql,  and a server for graphql and have some questions.

(Installed from source)

1) Doing: `#include <graphqlparser/JsonVisitor.h>` and getting 
```
/usr/local/include/graphqlparser/JsonVisitor.h:13:10: fatal error: 'AstVisitor.h' file not found
#include "AstVisitor.h"
         ^
1 error generated.
```
Mistake in the cmake installation?

2) Why is there a nested libgraphqlparser inside of graphqlparser in the installed headers?/

3) Twitter question

4) is `graphql_ast_to_json` intended just for debugging or is the graphql server intended to relevant info out of that and then do with the data as it wills, ie querying postgres, redis, etc. What are some more example C++ API based usages of the AST

**Comment by swolchok** [comment]
1) What's your build environment? I've got `/usr/local/include/graphqlparser/AstVisitor.h` in my install, which the quoted import should find IIUC.

2) That is an excellent question. I'm not sure how that got there. I'll have to look into it.

3) Answered on Twitter -- https://twitter.com/ScottWolchok/status/702974901511000064

4) It's an example. You *can* use it if you want to just process the AST as JSON, but if your program is written in C++ or in a language capable of directly calling C or C++ APIs, you'll get better performance using the library that way. I'm not aware of a real server implementation that uses libgraphqlparser directly right now :(

**Comment by fxfactorial** [comment]
1) Yep, its not installing it. 

Here is Ubuntu 14.04 VM install:

http://pastebin.com/QJXFZvpy

which oddly added stuff to `/var/empty`. After moving stuff to their appropriate places in `/usr/local` then I have this 
```
gar@osboxes:/usr/local/include/graphqlparser)-(88K:11)
> ls
./   AstNode.h  GraphQLParser.h  lexer.h            location.hh     position.hh  syntaxdefs.h
../  c/         JsonVisitor.h    libgraphqlparser/  parser.tab.hpp  stack.hh
```
which doesn't have AstVisitor.h.

2) thanks
3) Yes exactly but where are the method declarations? How can I know what methods are available on this object, I'm looking around and can't find it. 

which related to 4

4) I'm interested in using this directly for the directly via bindings but related to 3 I can't find the interface of a node. From the example I know it has a `get` method but what else? I looked through the Headers but can't seem to find it. Can you provide another example of where you're pulling something out of the parsed AST instead of turning it into JSON and giving to someone else to handle. I see the C based example but would prefer to stay with C++.

**Comment by swolchok** [comment]
1) My install was stale. I patched installation and pushed to master; we now actually install `Ast.h` and `AstVisitor.h`. Thanks for the bug report and sorry it took me a few days to get around to this.
3 & 4) There are very few methods you can call on `Node`, and they're all there in the header -- you get `accept` to apply a visitor and `getLocation` to get the source location. Methods available on the subclasses are in `Ast.h`, which should now be installed correctly.

**Comment by fxfactorial** [comment]
Thanks! This lets me continue my project.

**Comment by rmosolgo** [comment]
I was just catching up -- 

> a real server implementation that uses libgraphqlparser directly 

:tada: I finally got a proper Ruby extension going: https://github.com/rmosolgo/graphql-libgraphqlparser-ruby 

It even works on Heroku, thanks to https://github.com/goco-inc/heroku-buildpack-libgraphqlparser

So, thanks for the great project!
