### ISSUE TITLE
ArrayValue is used instead of ListValue

### ISSUE THREAD

**Issue by joshprice** [graphql/libgraphqlparser#27]
`ArrayValue` isn't referenced in the spec but `ListValue` is https://facebook.github.io/graphql/#sec-List-Value.

With a query like:

```graphql
{
  field(input: {a: ["bar"])
}
```

I get something like:

```json
"value": {
  "kind": "ArrayValue",
 ...
}
```

I'd expect:

```json
"value": {
  "kind": "ListValue",
 ...
}
```

which would mirror the spec

**Comment by swolchok** [comment]
Oh, this changed out from under me: https://github.com/graphql/graphql-js/commit/0f784fd83e98f908b54b1d51f6e79ba38549aed1

Good catch! Update coming.

**Comment by swolchok** [comment]
fixed by 5b836547c2887387e5db15a844a48fa4fd9bcbf8

**Comment by aarvay** [comment]
Thanks for the fix, @swolchok :+1:

**Comment by joshprice** [comment]
Thanks @swolchok, appreciate your work on this 🙏
