### ISSUE TITLE
Python version not used during install

### ISSUE THREAD

**Issue by svmnotn** [graphql/libgraphqlparser#28]
I have both python 3.5 and 2.7 installed in my machine (Arch Linux) but whenever I run the `cmake .` command it always picks `/usr/bin/python` which links to 3.5.

Currently I just made `/usr/bin/python` to point into 2.7 but it would be better if the build script would pick the correct one.

**Comment by swolchok** [comment]
Does https://github.com/graphql/libgraphqlparser/commit/af35863818c9dd901a2421f1e1fe5901859ae9d8 fix this for you?

**Comment by svmnotn** [comment]
Sadly it does not. CMake still errors out saying:
```
CMake Error at CMakeLists.txt:8 (MESSAGE):
  Python 2 is required.
```

**Comment by swolchok** [comment]
How about f4ec166f4f8e247e2eb1f360ca43bc25d691beec?

**Comment by svmnotn** [comment]
All that did was add:
```
-- Found PythonInterp: /usr/bin/python (found suitable version "3.5.1", minimum required is "2")
```
on top of the previous error. I should say that I did try that before submitting the issue.

**Comment by swolchok** [comment]
Interesting. I tried making my /usr/local/bin/python be python3 and it still found my python2 executable before asking, too.

**Comment by svmnotn** [comment]
For context when I run `ls -Al | grep python` inside of `/usr/bin`, it gives me
```
python -> python3
python2 -> python2.7
python2.7
python2.7-config
python2-config -> python2.7-config
python3 -> python3.5
python3.5
python3.5-config -> python3.5m-config
python3.5m
python3.5m-config
python3-config -> python3.5-config
python-config -> python3-config
```

**Comment by swolchok** [comment]
Google suggests that this is a widespread problem on Arch with projects that use CMake and want python2. The suggested workaround is `cmake -DPYTHON_EXECUTABLE=/path/to/python2.7`. See e.g. https://hub.qgis.org/issues/5069 https://github.com/jckarter/clay/issues/53
