### ISSUE TITLE
Statically linking library

### ISSUE THREAD

**Issue by calebmer** [graphql/libgraphqlparser#30]
I'm trying to write bindings for the Rust programming language. Is there a way to statically link this project?

**Comment by swolchok** [comment]
You can probably do what you want by fiddling with CMakeLists.txt. See https://cmake.org/cmake/help/v3.0/command/add_library.html for how to make it create a static library.

**Comment by rivanov2** [comment]
@calebmer I just had to do this, in case you've not figured it out, it's a simple change, as mentioned, to [CmakeLists.txt](https://github.com/graphql/libgraphqlparser/blob/master/CMakeLists.txt#L34).

`SHARED` -> `STATIC` should do the trick.
