### ISSUE TITLE
Pure C API doesn't provide a way to access individual list-style subnodes

### ISSUE THREAD

**Issue by martinandert** [graphql/libgraphqlparser#34]
For example: Given I have a handle to a `GraphQLAstSelectionSet`, I can access the number of selections contained within it by calling `GraphQLAstSelectionSet_get_selections_size`. But how do I get a handle to a specific selection in the list? Is there a way to enumerate the selections contained within the selection set without resorting to visitors?

This also applies to other nodes with subnode lists, e.g. Document -> definitions, FragmentSpread -> directives etc.

Disclaimer: As I'm fairly new to all this stuff, I may be missing something really obvious here.

**Comment by swolchok** [comment]
> Is there a way to enumerate the selections contained within the selection set without resorting to visitors?

The intent is to use a visitor. Without a visitor, you would have no way to determine the actual type (`Field`, `FragmentSpread`, or `InlineFragment`) of each of the selections in the `GraphQLAstSelectionSet` (`GraphQLAstSelection` is an abstract type).
