### ISSUE TITLE
Wrong includes in C API

### ISSUE THREAD

**Issue by dosten** [graphql/libgraphqlparser#38]
Hi!

I'm creating a PHP extension on top of this library, but I'm having trouble using the C API, these two includes seem to be wrong: https://github.com/graphql/libgraphqlparser/blob/master/c/GraphQLAstVisitor.h#L12-L13

I'm missing something or this is a bug?

**Comment by swolchok** [comment]
90383fb37016bf4890af975bd97d87c587a3d4d6 adds a C file that includes C API headers just to make sure they build OK. It builds, so I suspect you probably have your include paths set up incorrectly.
