### ISSUE TITLE
query kitchen sink nullish

### ISSUE THREAD

**Issue by schloerke** [graphql/libgraphqlparser#43]
A couple weeks ago they [updated support for nullish values in the query kitchen sink](https://github.com/graphql/graphql-js/blob/c23f5782dee81b0a59a6a6bb2bcca9da247570e7/src/language/__tests__/kitchen-sink.graphql#L55).  If this test could be added, that would great!

```
{
  unnamed(truthy: true, falsey: false, nullish: null),
  query
}
```

Thank you,
Barret

**Comment by swolchok** [comment]
This was implemented in bb2137cf1ec2c3f567d349de7479f9ac49fc3b2a shortly after it came out.
