### ISSUE TITLE
Support triple-quoted block strings

### ISSUE THREAD

**Issue by jeroen** [graphql/libgraphqlparser#44]
@schloerke has found in our R bindings that the [kitchen sink example](https://raw.githubusercontent.com/graphql/graphql-js/master/src/language/__tests__/kitchen-sink.graphql) produces invalid JSON:

```sh
curl -OL https://raw.githubusercontent.com/graphql/graphql-js/master/src/language/__tests__/kitchen-sink.graphql
./dump_json_ast kitchen-sink.graphql
```

The [output](http://pastebin.com/raw/xPMRm1yQ) has an invalid trailing comma (which you can validate on http://pro.jsonlint.com)

<img width="964" alt="screen shot 2016-12-19 at 9 15 38 pm" src="https://cloud.githubusercontent.com/assets/216319/21327618/58ee528c-c630-11e6-90e6-38f899f7b5b2.png">

**Comment by swolchok** [comment]
Good catch! The null value is a special case that I missed because it has no fields besides the source location.

**Comment by dvergeylen** [comment]
Hello,

I am afraid the kitchen test changed a few months ago. Testing on a fresh `clone` I get the following output:

```bash
$ # Init
$ git clone https://github.com/graphql/libgraphqlparser
$ cd libgraphqlparser/
$ cmake .
$ make

$ # Test
$ curl -OL https://raw.githubusercontent.com/graphql/graphql-js/master/src/language/__tests__/kitchen-sink.graphql
$ ./dump_json_ast kitchen-sink.graphql
Parser failed with error: 49.58-59: Unterminated string
```

Am I doing something wrong?
