### ISSUE TITLE
visit_argument crashed. Need a few help to guide how to fix it.

### ISSUE THREAD

**Issue by raykin** [graphql/libgraphqlparser#53]
I use Shopify/graphql-parser to write following ruby code but crashed in C 
```ruby 
    def visit_argument(arg)
      key = arg.name.value
      # TODO crashed in C trace
      value_obj = arg.value
    end
```
I debug the C code in graphql-parser, the visit_argument should defined in https://github.com/Shopify/graphql-parser/blob/master/ext/graphql_parser/graphql_ruby.c#L220
I'm new on both C and C++, so I don't know how to debug them.
I report an issue on https://github.com/Shopify/graphql-parser/issues/14 with C error trace but the shopify seems not maintenance the lib anymore.
Btw, The problem seems related to https://github.com/Shopify/graphql-parser/issues/4. But I just not understand it well.

Thanks for any help.

**Comment by swolchok** [comment]
As Shopify/graphql-parser#4 says, you can't use `value` directly. Define `visit_` methods for each of the subtypes of `Value`, either in your same visitor or in a subvisitor just for looking at arguments.
