### ISSUE TITLE
Support for defining a schema

### ISSUE THREAD

**Issue by Martinsos** [graphql/libgraphqlparser#54]
Hi, thank you for this project!
I am very new to GraphQL so forgive me if I am asking naive questions :).
I am considering implementing a graphql server in C++, and while I see that libgraphqlparser offer parsing of a graphql query, I could not find if it offers creating of Schema and executing query against it?

I know that in other languages(js) the idea is to generate the schema and then when query arrives it is parsed, validated and executed against the schema, so that is why I am looking for the libraries that would support the same thing in C++.

If there is support, would you mind sharing some code examples? Thanks!

**Comment by swolchok** [comment]
> creating of Schema
#45 added support for parsing the schema definition part of the language.

> executing query
executing a query is definitely out of scope for this project. As its name states, it is just for parsing. There are server libraries in a variety of programming languages listed at http://graphql.org/code/, but none of them appears to be in C++ yet.

**Comment by Martinsos** [comment]
Thanks a lot for the answer!

**Comment by emwalker** [comment]
Curious whether validating a GraphQL document against a parsed schema is in or out of scope for this project?

**Comment by emwalker** [comment]
Ok, just found [this](https://github.com/graphql/libgraphqlparser/blob/master/c/GraphQLParser.h#L44) and [this](https://github.com/graphql/libgraphqlparser/issues/22), which will perhaps answer my question.
