### ISSUE TITLE
Package-config in Homebrew

### ISSUE THREAD

**Issue by rex-remind101** [graphql/libgraphqlparser#59]
I'm looking for `libgraphqlparser.pc.in` in the Cellar library from a homebrew (`brew install libgraphqlparser`) installation and can't find it. Would be useful to have this available. How can we make this available?

**Comment by swolchok** [comment]
I just verified on master and `/usr/local/lib/pkgconfig/libgraphqlparser.pc` is installed by `make install`. The homebrew formula is entirely separate, and I'm not sure why it's not setting up `pkg-config` for you. I suggest you file an issue on homebrew instead.

**Comment by rex-remind101** [comment]
Unfortunately that's the first place I went I received this when trying to open an issue.
```
# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.
```
Guess my only option is hunting down the person who made the formulae?
