### ISSUE TITLE
Building / installing without sudo

### ISSUE THREAD

**Issue by bessey** [graphql/libgraphqlparser#65]
I've been spending time improving my Travis build times, and my final remaining task to switch to their container infrastructure is to get rid of the `sudo make install` required by `libgraphqlparser`.

I've spelunked the Makefile a little but I don't see an obvious way to encourage the installer to build to a directory I have access to instead of `/usr/local/include/graphqlparser`. Any suggestions?

**Comment by swolchok** [comment]
libgraphqlparser is built with cmake, so it supports whatever mechanisms your version of cmake supports for this. For example, see https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html#variable:CMAKE_INSTALL_PREFIX
