### ISSUE TITLE
Allow building C binding out of the box

### ISSUE THREAD

**Issue by gonzus** [graphql/libgraphqlparser#69]
If I missed something, my apologies, please point me in the right direction.

I would like to wrap this library in Perl. For that I need the C binding built as a dynamic library. This seems not to be supported out of the box.

I added a simple Makefile for my own purposes, and have no problem in creating a pull request for it. But since the project uses cmake, perhaps you would rather do this differently?

Thanks!

**Comment by swolchok** [comment]
The default out-of-box dynamic library should export both the C and C++ bindings and install headers for both. The C headers are in a subdirectory called `c`, so if you've installed graphqlparser's headers in /usr/local/include/graphqlparser and have that in your include path, you'd import them like `#include <graphqlparser/c/GraphQLParser.h>`

**Comment by gonzus** [comment]
You are absolutely right. Thanks for pointing me in the right direction!
