### ISSUE TITLE
better test instructions

### ISSUE THREAD

**Issue by gonzus** [graphql/libgraphqlparser#74]
The readme says:
```To run tests, please download googletest from https://github.com/google/googletest/archive/release-1.8.0.zip and unzip it in the test subdirectory.```

And that's it. I downloaded googletest in the test directory, ran cmake . and then tried with several make targets, but they all failed:

```libgraphqlparser/test/ParserTests.cpp:13:10: fatal error: 'Ast.h' file not found```

(after adding symlinks for the missing header files)

```libgraphqlparser/test/Ast.h:237:43: error: a space is required between consecutive right angle brackets (use '> >')```

I am pretty sure I missed a step here. Could some more detailed info be provided in the readme? Perhaps add a `test/README.md`?

**Comment by ErikWittern** [comment]
@gonzus Have you been able to figure this out? Running into the same problem.

**Comment by gonzus** [comment]
Nope, sorry @ErikWittern  -- and I am on holiday right now, so won't be able to test this for a few weeks.

**Comment by ErikWittern** [comment]
@gonzus No worries. I got the tests running and filed a [PR](https://github.com/graphql/libgraphqlparser/pull/84) to fix things and improve the documentation. The latest error you receive has to do with your compiler not targeting C++ 11, it seems.
